name: infra CI/CD Pipeline
# this will be the name of the run in the Actions tab ex: deploy-eks-on-dev-from-branch-main
run-name: ${{ github.event_name == 'workflow_dispatch' && format('#deploy-eks-on-{0}-from-branch-{3}', inputs.infra_path, github.ref_name) || '' }} 
on:
  workflow_dispatch:
    inputs:
      infra_path:
        description: 'target environment'
        type: choice
        options:
          - 'aws/dev/vpc'
          - 'aws/dev/eks'
          - 'aws/prod/vpc'
          - 'aws/prod/eks'
        required: true
        
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.inputs.infra_path }} # concurrency group to prevent multiple runs of the same workflow

jobs:
  terragrunt:
    name: Terraform Plan
    runs-on: ubuntu-latest  # should runs on GitHub-hosted runner
    env:
      TERRAGRUNT_PATH: ${{ github.event.inputs.infra_path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.4.6
      - name: Install Terragrunt
        run: |
          TG_VERSION=$(curl -s https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | jq -r .tag_name)
          curl -L https://github.com/gruntwork-io/terragrunt/releases/download/$TG_VERSION/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt
      - name: Initialize and run Terragrunt
        run: |
          cd $TERRAGRUNT_PATH
          terragrunt init
          terragrunt apply --auto-approve
        shell: bash
