name: Pre-commit
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
env:
  SKIP: check-git-config-email
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: terraform-linters/setup-tflint@v4
    - id: changed-files
      uses: tj-actions/changed-files@v45
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --files ${{ steps.changed-files.outputs.all_changed_files }}
